name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

  test:
    runs-on: ubuntu-latest
    needs: lint  # Ensures 'test' runs after 'lint'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensures 'deploy' runs only if 'test' is successful
    if: success()  # Ensures 'deploy' runs only if previous jobs were successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to server
        run: |
          echo "Deploying application..."
          # Add deployment commands here
          
      - name: Handle failure (optional step)
        if: failure()  # This block will run only if the 'deploy' step fails
        run: |
          echo "Deployment failed! Investigate previous job logs."
          # Optionally, you could notify via email, Slack, etc.
